name: Approval

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string
jobs:
  approval-request:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target }}
    steps:
    - name: dummy
      run: echo dummy step
