name: DeploymentChoice
description: 'request approval'

on:
  workflow_dispatch:
    inputs:
      timeslot:
        description: Please enter timeslot in format 'YYY-MM-DD HH:MM:SS'
        required: false
        type: string
      artifact:
        description: Artifact ID
        required: false
        type: string
      tenant:
        type: choice
        description: Which Tenant do you want to deploy?
        options: 
        - all
        - it
        - br
jobs:
  call-pipeline:
    runs-on: ubuntu-latest
    steps:
      uses: /DeploymentPipeline.yml
      with:
        tenant: ${{ inputs.tenant }}
        timeslot: ${{ inputs.timeslot }}
        artifact: ${{ inputs.artifact }}
