name: Matrix Test
# The trigger event for the workflow file to run 
on: 
  workflow_dispatch:

jobs:
  ReuseableMatrixJobForDeployment:
    strategy:
      matrix:
        target: [dev, stage, prod]
    uses: ./.github/workflows/ApprovalReusable.yml
    with:
      target: ${{ matrix.target }}
