name: Matrix Strategy Max-Parallel Sample
# The trigger event for the workflow file to run 
on: push

jobs:
  ReuseableMatrixJobForDeployment:
    strategy:
      matrix:
        target: [dev, stage, prod]
    uses: ./Actions-Test/.github/workflows/ApprovalReusable.yml
    with:
      target: ${{ matrix.target }}
